# Generated by Django 5.0.6 on 2024-05-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GENDER', models.CharField(max_length=50, null=True)),
                ('AGE', models.CharField(max_length=50, null=True)),
                ('NIR', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('L', models.CharField(max_length=50)),
                ('Timestamp', models.CharField(max_length=50)),
            ],
        ),
    ]
